filtro reportes
IngenieriaDeSistemasUTB/altem-utb pull request #23
Opened 2020-04-30 21:53 UTC by MauricioALP

Solución al Issue #9 el cual presentaba errores con el filtro de la pestaña reportes. Todo se encuentra funcional.

2020-04-30 21:55 UTC, MauricioALP commented on Dockerfile
> +VOLUME /altem /data/altem
La creación de este volumen acelera la instrucción en la linea siguiente: 
RUN chown -R www-data:www-data /altem/

2020-05-01 02:35 UTC, Charles06x commented on Dockerfile
> +VOLUME /altem /data/altem
Good work with this!

2020-05-01 02:41 UTC, jairoserrano commented on Dockerfile
> +VOLUME /altem /data/altem
osea que hora no se van a copiar los datos, si no tener un volumen externo? buen detalle.

2020-05-01 03:25 UTC, Charles06x commented on altem/app/Http/Controllers/ReporteController.php
> +        if ($anio!=null and $periodo != null and $riesgo != null and $factor == null) {
Tratemos de evitar comentarios y usémoslos solo cuando sean necesarios, y en ese caso, que sean descriptivos.

Para validar si una variable es distinto de `null` podemos evitar esa comparación, y para verificar que en efecto sea `null` tenemos una función 'helper' `is_null()`, esta validación se podría simplificar de la siguiente manera:

`if ($anio and $periodo and $riesgo and is_null($factor))`

2020-05-01 05:25 UTC, Charles06x commented on altem/app/Http/Controllers/ReporteController.php
> +        }
Esto lo podemos simplificar y formar un string completo para el filtro, de manera que en la query usemos la función `whereRaw()`

Por ejemplo: 
`if($periodo ){
     $dateFilter = ($periodo == 1) ? 'MONTH(fecha_reporte) < 7' : 'MONTH(fecha_reporte) > 6';
  }`

2020-05-01 05:27 UTC, Charles06x commented on altem/app/Http/Controllers/ReporteController.php
> +                ->where(\DB::raw('MONTH(fecha_reporte) '), $operator, $fecha)
Aquí podemos cambiar el `where()` por el `whereRaw()`
Y quedaría así (Con el string que se armó anteriormente):

`->whereRaw($dateFilter)`

2020-05-01 05:29 UTC, cacevedo-dev requested changes
Ey @MauricioALP revisa los comentarios que dejé. Algunos aplican para todos os filtros. Déjame saber si tienes algún comentario al respecto. 👍

2020-06-14 19:51 UTC, cacevedo-dev approved these changes
LGTM @MauricioALP

2020-06-14 20:06 UTC, merged